# Generated by Django 3.1.1 on 2020-10-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200924_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMultiMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('receivers', models.TextField(blank=True, max_length=200)),
                ('subject', models.TextField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.DateTimeField(null=True)),
            ],
        ),
    ]
