# Generated by Django 3.1.1 on 2020-10-03 02:41

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0010_sendmultimail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBiodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('created_by', models.CharField(choices=[('se', ' Self'), ('pa', 'Parents'), ('fr', 'Friedns'), ('re', 'Relatives'), ('ot', 'Others'), ('ns', 'Not Specified')], default='ns', max_length=2)),
                ('marital_Status', models.CharField(choices=[('yy', 'Married'), ('nn', 'Not Married'), ('ns', 'Not Specified')], default='ns', max_length=2)),
                ('height', models.CharField(blank=True, max_length=100)),
                ('physical_disability', models.CharField(choices=[('yy', 'Yes'), ('nn', 'No'), ('ns', 'Not Specified')], default='ns', max_length=2)),
                ('body_Weight', models.IntegerField(default=60)),
                ('complexion', models.CharField(choices=[('ff', 'Fair'), ('mm', 'Milky Fair'), ('vf', 'Very Fair'), ('br', 'Brown'), ('dd', 'Dark'), ('nn', 'Normal'), ('ns', 'Not Specified')], default='ns', max_length=2)),
                ('DOB', models.DateField(default=datetime.date.today)),
                ('Lives_in', models.CharField(blank=True, max_length=50)),
                ('religion', models.CharField(choices=[('hi', 'Hindu'), ('mu', 'Muslim'), ('si', 'Sikh'), ('pa', 'Parsi'), ('ns', 'Not Specified')], default='ns', max_length=2)),
                ('diet', models.CharField(choices=[('ve', 'Vegitarian'), ('nv', 'Non Vegetaria'), ('eg', 'Eagitarian'), ('ns', 'Not Specified')], default='ns', max_length=2)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('email_ID', models.CharField(default='', max_length=100)),
                ('is_Contact_visible', models.CharField(choices=[('yy', 'Yes'), ('nn', 'No'), ('ns', 'Not Specified')], default='ns', max_length=2)),
                ('Father_name', models.CharField(default='', max_length=100)),
                ('Mother_name', models.CharField(default='', max_length=100)),
                ('Family_details', models.CharField(blank=True, max_length=500)),
                ('Education', models.CharField(blank=True, max_length=100)),
                ('profession', models.CharField(choices=[('ac', 'Accountant'), ('te', 'Teacher'), ('tc', 'Technician'), ('la', 'Laborer'), ('ba', 'Banker'), ('fa', 'Farmer'), ('sh', 'Shop Keeper'), ('bm', 'Business Man'), ('en', 'Engineer'), ('do', 'Doctor'), ('ot', 'Others'), ('ns', 'Not Specified')], default='ns', max_length=2)),
                ('Income', models.CharField(blank=True, default='30k', max_length=100)),
                ('About', models.CharField(blank=True, max_length=500)),
                ('Photo', models.ImageField(default='default.jpg', upload_to='todo/images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
