# Generated by Django 3.1.1 on 2020-10-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_mybiodata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybiodata',
            old_name='About',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='mybiodata',
            old_name='Lives_in',
            new_name='annual_Income',
        ),
        migrations.RenameField(
            model_name='mybiodata',
            old_name='Education',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='mybiodata',
            old_name='Family_details',
            new_name='family_details',
        ),
        migrations.RenameField(
            model_name='mybiodata',
            old_name='Father_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='mybiodata',
            old_name='Mother_name',
            new_name='mother_name',
        ),
        migrations.RenameField(
            model_name='mybiodata',
            old_name='Photo',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='mybiodata',
            name='Income',
        ),
        migrations.RemoveField(
            model_name='mybiodata',
            name='is_Contact_visible',
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='body_Type',
            field=models.CharField(choices=[('sl', 'Slim'), ('av', 'Average'), ('ft', 'Fit'), ('he', 'Healthy'), ('ch', 'Chubby'), ('fa', 'Fatty'), ('ns', 'Not Specified')], default='av', max_length=2),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='cast',
            field=models.CharField(choices=[('ku', 'Kushwaha'), ('mr', 'Maurya'), ('sh', 'Shakya'), ('sa', 'Saini'), ('ns', 'Not Specified')], default='ns', max_length=2),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='contact_privacy',
            field=models.CharField(choices=[('pu', 'Visible To All'), ('pr', 'Visible To Me'), ('hi', 'Hidden'), ('ns', 'Not Specified')], default='ns', max_length=2),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='father_occupation',
            field=models.CharField(choices=[('ac', 'Accountant'), ('te', 'Teacher'), ('tc', 'Technician'), ('la', 'Laborer'), ('ba', 'Banker'), ('fa', 'Farmer'), ('sh', 'Shop Keeper'), ('bm', 'Business Man'), ('en', 'Engineer'), ('do', 'Doctor'), ('ot', 'Others'), ('ns', 'Not Specified')], default='ns', max_length=2),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='job_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='mother_Toung',
            field=models.CharField(choices=[('hi', 'Hindi'), ('en', 'English'), ('bt', 'Both'), ('ns', 'Not Specified')], default='hi', max_length=2),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='mother_occupation',
            field=models.CharField(choices=[('hw', 'House Wife'), ('ac', 'Accountant'), ('te', 'Teacher'), ('tc', 'Technician'), ('la', 'Laborer'), ('ba', 'Banker'), ('fa', 'Farmer'), ('sh', 'Shop Keeper'), ('bm', 'Business Man'), ('en', 'Engineer'), ('do', 'Doctor'), ('ot', 'Others'), ('ns', 'Not Specified')], default='hw', max_length=2),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='profession_type',
            field=models.CharField(choices=[('pr', 'Private'), ('go', 'Government'), ('sg', 'Semi Govt'), ('ca', 'Contratual'), ('ot', 'Others'), ('ns', 'Not Specified')], default='ns', max_length=2),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='social',
            field=models.CharField(choices=[('re', 'Religious Background'), ('nr', 'Normal'), ('bt', 'Both'), ('ns', 'Not Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='email_ID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
