# Generated by Django 3.1.1 on 2020-10-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20201003_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybiodata',
            name='gender',
            field=models.CharField(choices=[('fe', 'Female'), ('ma', 'Male'), ('ns', 'Not Specified')], default='ns', max_length=2),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='hobbies',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
