# Generated by Django 3.1.1 on 2020-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20201003_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybiodata',
            name='manglik',
            field=models.CharField(choices=[('fe', 'Yes'), ('ma', 'No'), ('ns', 'Not_Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='body_Type',
            field=models.CharField(choices=[('sl', 'Slim'), ('av', 'Average'), ('ft', 'Fit'), ('he', 'Healthy'), ('ch', 'Chubby'), ('fa', 'Fatty'), ('ns', 'Not_Specified')], default='av', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='cast',
            field=models.CharField(choices=[('ku', 'Kushwaha'), ('mr', 'Maurya'), ('sh', 'Shakya'), ('sa', 'Saini'), ('ns', 'Not_Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='complexion',
            field=models.CharField(choices=[('ff', 'Fair'), ('mm', 'Milky_Fair'), ('vf', 'Very_Fair'), ('br', 'Brown'), ('dd', 'Dark'), ('nn', 'Normal'), ('ns', 'Not_Specified')], default='ff', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='contact_privacy',
            field=models.CharField(choices=[('pu', 'Visible_To_All'), ('pr', 'Visible_To_me'), ('hi', 'Hidden'), ('ns', 'Not_Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='created_by',
            field=models.CharField(choices=[('se', '_Self'), ('pa', 'Parents'), ('fr', 'Friedns'), ('re', 'Relatives'), ('ot', 'Others'), ('ns', 'Not_Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='diet',
            field=models.CharField(choices=[('ve', 'Vegitarian'), ('nv', 'Non_Vegetaria'), ('eg', 'Eagitarian'), ('ns', 'Not_Specified')], default='ve', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='father_occupation',
            field=models.CharField(choices=[('ac', 'Accountant'), ('te', 'Teacher'), ('tc', 'Technician'), ('la', 'Laborer'), ('ba', 'Banker'), ('fa', 'Farmer'), ('sh', 'Shop_Keeper'), ('bm', 'Business_Man'), ('en', 'Engineer'), ('do', 'Doctor'), ('ot', 'others'), ('ns', 'Not_Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='gender',
            field=models.CharField(choices=[('fe', 'Female'), ('ma', 'Male'), ('ns', 'Not_Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='marital_Status',
            field=models.CharField(choices=[('yy', 'married'), ('nn', 'Not_married'), ('ns', 'Not_Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='mother_Toung',
            field=models.CharField(choices=[('hi', 'Hindi'), ('en', 'English'), ('bt', 'Both'), ('ns', 'Not_Specified')], default='hi', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='mother_occupation',
            field=models.CharField(choices=[('hw', 'House_wife'), ('ac', 'Accountant'), ('te', 'Teacher'), ('tc', 'Technician'), ('la', 'Laborer'), ('ba', 'Banker'), ('fa', 'Farmer'), ('sh', 'Shop_Keeper'), ('bm', 'Business_Man'), ('en', 'Engineer'), ('do', 'Doctor'), ('ot', 'others'), ('ns', 'Not_Specified')], default='hw', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='physical_disability',
            field=models.CharField(choices=[('yy', 'Yes'), ('nn', 'No'), ('ns', 'Not_Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='profession',
            field=models.CharField(choices=[('ac', 'Accountant'), ('te', 'Teacher'), ('tc', 'Technician'), ('la', 'Laborer'), ('ba', 'Banker'), ('fa', 'Farmer'), ('sh', 'Shop_Keeper'), ('bm', 'Business_Man'), ('en', 'Engineer'), ('do', 'Doctor'), ('ot', 'others'), ('ns', 'Not_Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='profession_type',
            field=models.CharField(choices=[('pr', 'Private'), ('go', 'Government'), ('sg', 'Semi_Govt'), ('ca', 'Contratual'), ('ot', 'Others'), ('ns', 'Not_Specified')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='religion',
            field=models.CharField(choices=[('hi', 'Hindu'), ('mu', 'Muslim'), ('si', 'Sikh'), ('pa', 'Parsi'), ('ns', 'Not_Specified')], default='hi', max_length=2),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='social',
            field=models.CharField(choices=[('re', 'Religious_Background'), ('nr', 'Normal'), ('bt', 'Both'), ('ns', 'Not_Specified')], default='re', max_length=2),
        ),
    ]
