# Generated by Django 3.1.1 on 2020-10-03 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20201003_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybiodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='deletedrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='last_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
