# Generated by Django 3.1.1 on 2020-10-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20201003_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybiodata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
