# Generated by Django 3.1.1 on 2020-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_auto_20201003_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodataPrivacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_visibility', models.CharField(choices=[('Visible_To_All', 'Visible To All'), ('Visible_To_ME', 'Visible To Me'), ('Hidden', 'Hidden'), ('Not_Specified', 'Not Specified')], default='Visible_To_ME', max_length=20)),
                ('email_visibility', models.CharField(choices=[('Visible_To_All', 'Visible To All'), ('Visible_To_ME', 'Visible To Me'), ('Hidden', 'Hidden'), ('Not_Specified', 'Not Specified')], default='Visible_To_ME', max_length=20)),
                ('education_detail_visibility', models.CharField(choices=[('Visible_To_All', 'Visible To All'), ('Visible_To_ME', 'Visible To Me'), ('Hidden', 'Hidden'), ('Not_Specified', 'Not Specified')], default='Visible_To_ME', max_length=20)),
                ('address_detail_visibility', models.CharField(choices=[('Visible_To_All', 'Visible To All'), ('Visible_To_ME', 'Visible To Me'), ('Hidden', 'Hidden'), ('Not_Specified', 'Not Specified')], default='Visible_To_ME', max_length=20)),
                ('hide_profile', models.CharField(choices=[('Hidden', 'Hidden'), ('Show', 'Show'), ('Not_Specified', 'Not Specified')], default='Show', max_length=20)),
            ],
        ),
    ]
