# Generated by Django 3.1.1 on 2020-10-03 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0019_biodataprivacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodataprivacy',
            name='biodataid',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='biodataprivacy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biodataprivacy',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
