# Generated by Django 3.1.1 on 2020-10-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_auto_20201003_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodataprivacy',
            old_name='biodataid',
            new_name='bioid',
        ),
    ]
