# Generated by Django 3.1.1 on 2020-10-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_auto_20201003_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodataprivacy',
            old_name='bioid',
            new_name='biodataid',
        ),
    ]
