# Generated by Django 3.1.1 on 2020-10-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_auto_20201003_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybiodata',
            name='address_detail_visibility',
            field=models.CharField(choices=[('Visible_To_All', 'Visible To All'), ('Visible_To_ME', 'Visible To Me'), ('Hidden', 'Hidden'), ('Not_Specified', 'Not Specified')], default='Visible_To_All', max_length=20),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='contact_visibility',
            field=models.CharField(choices=[('Visible_To_All', 'Visible To All'), ('Visible_To_ME', 'Visible To Me'), ('Hidden', 'Hidden'), ('Not_Specified', 'Not Specified')], default='Visible_To_ME', max_length=20),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='education_detail_visibility',
            field=models.CharField(choices=[('Visible_To_All', 'Visible To All'), ('Visible_To_ME', 'Visible To Me'), ('Hidden', 'Hidden'), ('Not_Specified', 'Not Specified')], default='Visible_To_All', max_length=20),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='email_visibility',
            field=models.CharField(choices=[('Visible_To_All', 'Visible To All'), ('Visible_To_ME', 'Visible To Me'), ('Hidden', 'Hidden'), ('Not_Specified', 'Not Specified')], default='Visible_To_ME', max_length=20),
        ),
        migrations.AddField(
            model_name='mybiodata',
            name='hide_profile',
            field=models.CharField(choices=[('Hidden', 'Hidden'), ('Show', 'Show'), ('Not_Specified', 'Not Specified')], default='Show', max_length=20),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='contact_privacy',
            field=models.CharField(choices=[('Visible_To_All', 'Visible To All'), ('Visible_To_ME', 'Visible To Me'), ('Hidden', 'Hidden'), ('Not_Specified', 'Not Specified')], default='Not_Specified', max_length=20),
        ),
    ]
