# Generated by Django 3.1.1 on 2020-10-04 04:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0025_mybiochatbox_mybiodatainbox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyBioChatbox',
            new_name='MyBiodataChatbox',
        ),
    ]
