# Generated by Django 3.1.1 on 2020-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_auto_20201004_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodataHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(default='name', max_length=100)),
                ('query', models.TextField(blank=True)),
            ],
        ),
    ]
