# Generated by Django 3.1.1 on 2020-10-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0029_requestsforapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsforapproval',
            name='requesttoemailid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
