# Generated by Django 3.1.1 on 2020-10-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_requestsforapproval_requesttoemailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsforapproval',
            name='userbiodataid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
