# Generated by Django 3.1.1 on 2020-10-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_requestsforapproval_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsforapproval',
            name='requesttousername',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
