# Generated by Django 3.1.1 on 2020-10-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0034_requestsforapproval_requesttobiodataid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybiodatainbox',
            name='mybiodataid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
