# Generated by Django 3.1.2 on 2020-10-09 06:14

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0035_mybiodatainbox_mybiodataid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybiodata',
            name='DOB',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='annual_Income',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='cast',
            field=models.CharField(choices=[('Kushwaha', 'Kushwaha'), ('Maurya', 'Maurya'), ('Shakya', 'Shakya'), ('Saini', 'Saini'), ('Not_Specified', 'Not Specified')], default='Kushwaha', max_length=20),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='contact_privacy',
            field=models.CharField(choices=[('Visible_To_All', 'Visible To All'), ('Visible_To_ME', 'Visible To Me'), ('Hidden', 'Hidden'), ('Not_Specified', 'Not Specified')], default='Visible_To_All', max_length=20),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='created_by',
            field=models.CharField(choices=[('_Self', ' Self'), ('Parents', 'Parents'), ('Friedns', 'Friedns'), ('Relatives', 'Relatives'), ('Others', 'Others'), ('Not_Specified', 'Not Specified')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='education',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='father_occupation',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('Teacher', 'Teacher'), ('Technician', 'Technician'), ('Laborer', 'Laborer'), ('Banker', 'Banker'), ('Farmer', 'Farmer'), ('Shop_Keeper', 'Shop Keeper'), ('Business_Man', 'Business Man'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Lawyer', 'Lawyer'), ('others', 'Others'), ('Not_Specified', 'Not Specified')], default='Not_Specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='job_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='manglik',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not_Specified', 'Not Specified')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='marital_Status',
            field=models.CharField(choices=[('married', 'Married'), ('Never_married', 'Never Married'), ('Not_Specified', 'Not Specified')], default='Never_married', max_length=20),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=100, size=[400, 360], upload_to='todo/images/'),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='physical_disability',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not_Specified', 'Not Specified')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='place',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mybiodata',
            name='profession',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('Teacher', 'Teacher'), ('Technician', 'Technician'), ('Laborer', 'Laborer'), ('Banker', 'Banker'), ('Farmer', 'Farmer'), ('Shop_Keeper', 'Shop Keeper'), ('Business_Man', 'Business Man'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Lawyer', 'Lawyer'), ('others', 'Others'), ('Not_Specified', 'Not Specified')], default='Not_Specified', max_length=20),
        ),
    ]
